import { useState } from 'react';
import { ApiError, openCase } from '../api/client';
import type { CaseRecord } from '../api/types';
import { StatusMessage } from './StatusMessage';

export function OpenCasePanel() {
  const [filingId, setFilingId] = useState('');
  const [paymentId, setPaymentId] = useState('');
  const [openedCase, setOpenedCase] = useState<CaseRecord | null>(null);
  const [error, setError] = useState('');
  const [conflict, setConflict] = useState(false);
  const [busy, setBusy] = useState(false);

  async function submit() {
    const filing = filingId.trim();
    const payment = paymentId.trim();
    if (!filing || !payment) {
      setError('Filing ID and confirmed payment ID are required.');
      setConflict(false);
      return;
    }

    setBusy(true);
    setError('');
    setConflict(false);
    try {
      const result = await openCase(filing, payment);
      setOpenedCase(result);
    } catch (cause) {
      if (cause instanceof ApiError && cause.kind === 'conflict') {
        setConflict(true);
        setError('Case-opening eligibility changed or the requested transition is no longer valid. Review the current filing and payment state, then retry.');
      } else {
        setError('The case could not be opened.');
      }
    } finally {
      setBusy(false);
    }
  }

  return (
    <section aria-labelledby="open-case-heading">
      <h3 id="open-case-heading">Open eligible case</h3>
      <p>The case number is generated by the DCIECMS server only after eligibility checks succeed.</p>
      {error ? <StatusMessage kind="error" message={error} /> : null}
      <div>
        <label htmlFor="case-filing-id">Filing ID</label>
        <input id="case-filing-id" value={filingId} onChange={(event) => setFilingId(event.target.value)} disabled={busy} />
      </div>
      <div>
        <label htmlFor="case-payment-id">Confirmed payment ID</label>
        <input id="case-payment-id" value={paymentId} onChange={(event) => setPaymentId(event.target.value)} disabled={busy} />
      </div>
      <button type="button" onClick={() => void submit()} disabled={busy}>{conflict ? 'Retry case opening' : 'Open case'}</button>

      {openedCase ? (
        <section aria-label="Opened case">
          <h4>Case opened</h4>
          <dl>
            <div><dt>Case number</dt><dd>{openedCase.caseNumber}</dd></div>
            <div><dt>Status</dt><dd>{openedCase.status}</dd></div>
          </dl>
        </section>
      ) : null}
    </section>
  );
}
